version: '3.8'

services:
    postgres:
        container_name: mirea_backend_course_work_db
        image: postgres
        restart: on-failure
        environment:
            POSTGRES_USER: appUser
            POSTGRES_PASSWORD: appPassword
            POSTGRES_DB: appDb
        volumes:
            - ./Database:/docker-entrypoint-initdb.d
            - database:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        # webapp:
        #     build: Barbershop/.
        #     ports:
        #         - '8080:8080'
        #     container_name: mirea_backend_course_work_app
volumes:
    database: