INSERT INTO services (name, description, duration, price) VALUES ('Haircut', 'Classic mens haircut', 1800000, 2000);
INSERT INTO services (name, description, duration, price) VALUES ('Beard Trim', 'Trim and shape beard', 900000, 1500);
INSERT INTO services (name, description, duration, price) VALUES ('Shave', 'Traditional straight razor shave', 1200000, 2500);
INSERT INTO services (name, description, duration, price) VALUES ('Hair Color', 'Single-process color', 3600000, 4000);
INSERT INTO services (name, description, duration, price) VALUES ('Highlights', 'Partial highlights', 2400000, 3500);
INSERT INTO services (name, description, duration, price) VALUES ('Balayage', 'Balayage highlights', 4200000, 5000);
INSERT INTO services (name, description, duration, price) VALUES ('Blowout', 'Blow dry and style', 1500000, 2000);
INSERT INTO services (name, description, duration, price) VALUES ('Updo', 'Formal updo', 2400000, 3000);
INSERT INTO services (name, description, duration, price) VALUES ('Bridal Hair', 'Bridal hair trial and wedding day style', 6000000, 8000);
INSERT INTO services (name, description, duration, price) VALUES ('Extensions', 'Sew-in extensions', 7200000, 10000);
INSERT INTO services (name, description, duration, price) VALUES ('Brazilian Keratin Treatment', 'Semi-permanent hair smoothing treatment', 5400000, 6000);
INSERT INTO services (name, description, duration, price) VALUES ('Facial', 'Deep-cleansing facial', 3600000, 3500);

INSERT INTO barbers (name) VALUES ('John Doe');
INSERT INTO barbers (name) VALUES ('Jane Smith');
INSERT INTO barbers (name) VALUES ('David Lee');
INSERT INTO barbers (name) VALUES ('Sarah Kim');
INSERT INTO barbers (name) VALUES ('Michael Wong');
INSERT INTO barbers (name) VALUES ('Emily Chen');
INSERT INTO barbers (name) VALUES ('Tom Nguyen');

insert into barber_service (id_barber, id_service) values (1, 1);
insert into barber_service (id_barber, id_service) values (1, 2);
insert into barber_service (id_barber, id_service) values (1, 3);
insert into barber_service (id_barber, id_service) values (1, 4);
insert into barber_service (id_barber, id_service) values (1, 5);
insert into barber_service (id_barber, id_service) values (1, 6);
insert into barber_service (id_barber, id_service) values (1, 7);
insert into barber_service (id_barber, id_service) values (1, 8);
insert into barber_service (id_barber, id_service) values (1, 9);
insert into barber_service (id_barber, id_service) values (1, 10);
insert into barber_service (id_barber, id_service) values (1, 11);
insert into barber_service (id_barber, id_service) values (1, 12);
insert into barber_service (id_barber, id_service) values (2, 4);
insert into barber_service (id_barber, id_service) values (2, 12);
insert into barber_service (id_barber, id_service) values (2, 11);
insert into barber_service (id_barber, id_service) values (3, 10);
insert into barber_service (id_barber, id_service) values (3, 9);
insert into barber_service (id_barber, id_service) values (3, 12);
insert into barber_service (id_barber, id_service) values (3, 11);
insert into barber_service (id_barber, id_service) values (3, 4);
insert into barber_service (id_barber, id_service) values (3, 6);
insert into barber_service (id_barber, id_service) values (4, 7);
insert into barber_service (id_barber, id_service) values (4, 5);
insert into barber_service (id_barber, id_service) values (4, 8);
insert into barber_service (id_barber, id_service) values (4, 9);
insert into barber_service (id_barber, id_service) values (4, 6);
insert into barber_service (id_barber, id_service) values (4, 1);
insert into barber_service (id_barber, id_service) values (4, 4);
insert into barber_service (id_barber, id_service) values (4, 10);
insert into barber_service (id_barber, id_service) values (4, 11);
insert into barber_service (id_barber, id_service) values (5, 5);
insert into barber_service (id_barber, id_service) values (6, 1);
insert into barber_service (id_barber, id_service) values (6, 2);
insert into barber_service (id_barber, id_service) values (6, 3);
insert into barber_service (id_barber, id_service) values (6, 4);
insert into barber_service (id_barber, id_service) values (6, 5);
insert into barber_service (id_barber, id_service) values (6, 6);
insert into barber_service (id_barber, id_service) values (6, 7);
insert into barber_service (id_barber, id_service) values (7, 5);
insert into barber_service (id_barber, id_service) values (7, 6);
insert into barber_service (id_barber, id_service) values (7, 7);
insert into barber_service (id_barber, id_service) values (7, 8);
insert into barber_service (id_barber, id_service) values (7, 9);
insert into barber_service (id_barber, id_service) values (7, 10);